image: arduino-cli

stages:
- compile
- deploy


compile:
  script:
  - arduino-cli lib install "MySensors"
  - arduino-cli lib install "Bounce2"
  - arduino-cli compile --fqbn arduino:avr:mega App
  stage: compile


deploy production:
  when: manual
  only:
    refs:
      - master
  script:
  - curl -X POST -F token=$ENV_DEPLOY_AUTH_TOKEN -F ref=master -F "variables[BUILD_SOURCE]=arduinoLanguage" -F "variables[APP_COMMIT_SHA]=$CI_COMMIT_SHA" $ENV_DEPLOY_PROD_PIPELINE_API_URL
  stage: deploy